a = input("Digite algo:")
print("O tipo primitivo desse valor é {}".format(type(a)))
print('Só tem espaço?', a.isspace())
print("É um número?{}".format(a.isnumeric()))
print("É alfabetico?", a.isalpha())
print("É alfanumérico?{}".format(a.isalnum()))
print("Esta em maiuscula?", a.isupper())
print(f"Esta em minuscula? {a.islower()}")
print(f"Esta capsulada?{a.istitle()}")